In [1]:
import numpy as np

In [19]:
# create array
# 메소드와 멤버: dtype, ndim, shape, size

arr = np.arange(15) # 1차원 배열로 반환
arr = arr.reshape(3,5) # 3행 5열로 반환
print(arr,type(arr))
print()
print("배열의 차원:", arr.ndim)
print("배열의 행과 열:", arr.shape)
print("배열의 사이즈(총개수):", arr.size)
print("배열의 각 요소의 데이터 타입:", arr.dtype, arr.dtype.name, arr.dtype.itemsize) #dtype.name 데이터 타입의 이름
print()

arr1 = np.arange(-5, 5, 0.5) # -5부터 5 전까지 -0.5씩 증가
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>

배열의 차원: 2
배열의 행과 열: (3, 5)
배열의 사이즈(총개수): 15
배열의 각 요소의 데이터 타입: int32 int32 4

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5]


In [21]:
# list로 배열 생성
a1 = np.array([1.0, 2.0, 3.0])
print(a1, type(a1), a1.shape, a1.dtype)
print()
a2 = np.array([[1.0, 2.0, 3.0],[1.0, 2.0, 3.0]])
print(a2, type(a2), a2.ndim, a2.shape, a2.dtype)

[1. 2. 3.] <class 'numpy.ndarray'> (3,) float64

[[1. 2. 3.]
 [1. 2. 3.]] <class 'numpy.ndarray'> 2 (2, 3) float64


In [22]:
a = np.zeros(5)
b = np.zeros((2, 3))
c = np.zeros((5, 2), dtype="i") # int32
d = np.zeros(5, dtype="U4") # U->문자열
e = np.ones((2, 3, 4), dtype="i8") # int64
f = np.ones_like(b, dtype="f") # 실수형, float64
g = np.empty((4, 3))

In [29]:
print(g)

[[1.00403665e-311 2.81617418e-322 0.00000000e+000]
 [0.00000000e+000 1.01855798e-312 3.69776220e-062]
 [4.46458284e-090 3.11289055e-032 5.41398697e-067]
 [4.71379415e-062 6.48224660e+170 4.93432906e+257]]


In [30]:
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]) 
y2 = np.array([[5.0,10.0],[15.0,20.0]]) 
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

In [41]:
# array 기본 연산
print(x1+y1) # np.array([ 6. 12. 18.])
print(x1-y1) # np.array([ -4. -8. -12.])
print(x1*y1) # np.array([ 5. 20. 45.])
print(x1/y1) # np.array([ 0.2 0.2 0.2])
print()
print(x2+y2) # np.array([[ 6. 12.][ 18. 24.]])
print(x2-y2)
print(x2*y2)
print(x2/y2)
print()

# 행과 열의 갯수가 다른 경우: broadcast
print(x2+z1)
print(x2-z1)
print(x2*z1)
print(x2/z1)

print()
print(x1 ** 2)
print(x1 >= 2) # boolen 리턴

[ 6. 12. 18.]
[ -4.  -8. -12.]
[ 5. 20. 45.]
[0.2 0.2 0.2]

[[ 6. 12.]
 [18. 24.]]
[[ -4.  -8.]
 [-12. -16.]]
[[ 5. 20.]
 [45. 80.]]
[[0.2 0.2]
 [0.2 0.2]]

[[0. 0.]
 [2. 2.]]
[[2. 4.]
 [4. 6.]]
[[-1. -4.]
 [-3. -8.]]
[[-1. -1.]
 [-3. -2.]]

[1. 4. 9.]
[False  True  True]


In [50]:
# shape 변경
print(x2)
print(x2.flatten()) #모든 차수를 1차원으로 변경
# x2.reshape(-1,) #1차원으로 변경
x3 = x2.reshape(x2.size,) # 1차원으로 변경
print(x3.shape)
print(x3.reshape(2,2))

[[1. 2.]
 [3. 4.]]
[1. 2. 3. 4.]
(4,)
[[1. 2.]
 [3. 4.]]


In [62]:
x = np.arange(20)
x.reshape(2,2,5).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
# 인덱싱, 슬라이싱, 이터레이팅
a = np.arange(10)**2
print(a)
print(a[2])
print(a[3:5])
a[0:6:2] = -a[0:6:2]
print(a)
print(a[::-1]) # 뒤에서 부터 출력

print(a+1)

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[  0   1  -4   9 -16  25  36  49  64  81]
[ 81  64  49  36  25 -16   9  -4   1   0]
[  1   2  -3  10 -15  26  37  50  65  82]


In [88]:
a = np.arange(1,21,1).reshape(4,5)
print(a)
print()
print(a[2,3]) # 2행 3열
print(a[0:4,1]) # 0~4행 1열
print(a[1,]) # 1행
print(a[-1,1]) # 마지막행 1열
print(a[:,-1]) # 마지막열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

14
[ 2  7 12 17]
[ 6  7  8  9 10]
17
[ 5 10 15 20]


In [94]:
a = np.arange(6)
print(a)
print(np.sin(a)) 
print(np.cos(a))
print(np.tanh(a))
print(np.exp(a)) # 지수함수

[0 1 2 3 4 5]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


In [141]:
a1 = np.array([2,3,4])
a2 = np.array([1,5,2])

print(np.maximum(a1,a2)) # a1 a2 각 위치에서 최대값
print(np.minimum(a1,a2)) # a1 a2 각 위치에서 최소값

print(np.sum(a1)) #9
print(np.random.choice(100,5)) # 0~100 사이 중 5개 선택

print(np.random.choice(5,3,p=[0.1, 0, 0.3, 0.6, 0])) # p= 가중치 설정(합은 1)

[2 5 4]
[1 3 2]
9
[22 80 10 29 97]
[3 2 3]


In [146]:
np.random.rand(2,3) # 2열 3행의 랜덤 값 리턴(0과 1사이의 float)

array([[0.84042579, 0.75414333, 0.36815904],
       [0.53401055, 0.63136879, 0.53613804]])

In [147]:
np.random.randn(2,3) # 2열 3행의 표준 정규분포로 초기화

array([[ 0.9302622 ,  0.47267782,  0.56030077],
       [-0.25598879,  0.38369554, -0.37924496]])

In [182]:
np.random.randint(10) # 0~10사이(9) 까지 임의의 int 리턴

0

In [187]:
a = np.array([6,2,3,1,4,5])
print(a)

[6 2 3 1 4 5]


In [191]:
# 최대값의 위치 출력 argmax(), 최소값의 위치 출력 argmin()
print(np.argmax(a), a[np.argmax(a)]) # 인덱스 리턴, 값 리턴
print(np.argmin(a)) # 인덱스 리턴

0 6
3


In [192]:
a = np.array([[0.1,0.8,0.2],[0.3,0.2,0.5],[0.9,0.5,0.3]]) 
a

array([[0.1, 0.8, 0.2],
       [0.3, 0.2, 0.5],
       [0.9, 0.5, 0.3]])

In [199]:
# ★ 중요 ★
print(np.argmax(a)) # 0부터 1씩 증가.. 끝까지, 행 -> 열의 순서로
print(np.argmax(a, axis=1)) # 각 행마다 최대값 인덱스 리턴(x축)
print(np.argmax(a, axis=0)) # 각 열마다 최대값 인덱스 리턴(y축)

6
[1 2 0]
[2 0 1]


In [202]:
# 기술 통계 함수
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8, 2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])


In [218]:
print(len(x)) #데이터의 갯수
print('평균 >', np.mean(x))
print('분산 >', np.var(x))
print('표준편차 >', np.std(x))
print('최대값 >', np.max(x))
print('최소값 >', np.min(x))
print('중앙값 >', np.median(x))
print('1사분위수 >', np.percentile(x, 25)) # 25분위 수
print('2사분위수 >', np.percentile(x, 50)) # 중앙값
print('3사분위수 >', np.percentile(x, 75)) # 75분위 수
print('4사분위수 >', np.percentile(x, 100)) # 최대값


26
평균 > 4.8076923076923075
분산 > 115.23224852071006
표준편차 > 10.734628476137871
최대값 > 23
최소값 > -24
중앙값 > 5.0
1사분위수 > 0.0
2사분위수 > 5.0
3사분위수 > 10.0
4사분위수 > 23.0


In [228]:
# 난수 발생과 카운팅
np.random.seed(0) # 시작 숫자를 정해 주면 항상 같은 숫자의 난수 발생
np.random.rand(5) # 난수 5개 발생

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [255]:
np.random.seed(10)
x = np.arange(10)
print(x)

np.random.choice(x, 5)

[0 1 2 3 4 5 6 7 8 9]


array([9, 4, 0, 1, 9])

In [264]:
np.random.shuffle(x) # 원래의 array를 섞음
x

array([1, 6, 7, 3, 0, 9, 8, 2, 5, 4])

In [276]:
np.random.choice(x, len(x), replace=True) # replace=True 중복 허용, False 중복 X

array([6, 5, 1, 9, 4, 5, 9, 2, 5, 9])

In [288]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 0부터 5까지 수에서 10개를 뽑는데 p 가중치를 준다.

array([0, 0, 2, 0, 2, 3, 3, 2, 3, 3])

In [302]:
print(np.random.rand(10)) # 0부터 1사이의 실수 난수 생성
print(np.random.randn(10)) # 기대값 0, 표준편차 1인 가우시안 표준 정규 분포 따르는 난수 생성

print(np.random.randint(10,size=10)) # 0부터 10까지, 10개 생성
print(np.random.randint(10,20,size=10)) # 10부터 20까지, 10개 생성
print(np.random.randint(10,20,size=(3,5))) # 10부터 20까지, 3행 5열 15개 생성

[0.36632897 0.58990679 0.75923894 0.32235078 0.50202215 0.58383107
 0.26660088 0.71384664 0.45727111 0.65023137]
[-2.81600122  0.10954443  0.14266929 -0.78403556  0.25761074  1.31292275
 -1.34902537  0.50013685 -0.98458665  1.48597941]
[2 6 4 6 7 0 2 5 1 3]
[18 12 15 14 14 15 12 13 14 11]
[[15 18 10 10 14]
 [15 11 12 18 10]
 [15 12 12 14 16]]


In [325]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#이 배열에서 3의 배수를 찾아라.
a = list(x for x in range(1,len(x)) if x%3 == 0)
print(a)

#이 배열에서 4로 나누면 1이 남는 수를 찾아라.
b = list(x for x in range(len(x)) if x%4 == 1)
print(b)

#이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(set(a) & set(b))


[3, 6, 9, 12, 15, 18]
[1, 5, 9, 13, 17]
{9}


In [331]:
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
